### ISSUE TITLE
TypeError: Can't convert 'int' object to str implicitly

### ISSUE THREAD

**Issue by radekludacka** [NikolaiT/GoogleScraper#104]
When I invoke application by command:
GoogleScraper -m http-async --keyword-file keywords.txt -v3

It throws exception:
Traceback (most recent call last):
  File "/usr/local/bin/GoogleScraper", line 9, in <module>
    load_entry_point('GoogleScraper==0.1.37', 'console_scripts', 'GoogleScraper')()
  File "/usr/local/lib/python3.4/dist-packages/GoogleScraper/core.py", line 439, in main
    scheduler.run()
  File "/usr/local/lib/python3.4/dist-packages/GoogleScraper/async_mode.py", line 124, in run
    scrape = task.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 300, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.4/dist-packages/GoogleScraper/async_mode.py", line 51, in request
    self.status = 'not successful: ' + response.status
TypeError: Can't convert 'int' object to str implicitly

It is only necessary to replace line 51 of file GoogleScraper/async_mode.py:

self.status = 'not successful: ' + response.status
by 
self.status = 'not successful: ' + str(response.status)

**Comment by NikolaiT** [comment]
Thanks and fixxed.
