### ISSUE TITLE
GoogleScraper with python-anaconda

### ISSUE THREAD

**Issue by paulz1** [NikolaiT/GoogleScraper#108]
I use python 2.6 on my system, so to install GoogleScraper I installed python-anaconda ( https://store.continuum.io/cshop/anaconda/ ) which is Python 3.4.3.

Then I installed GoogleScraper using pip. It was installed without problem.
All of dependencies are present as well.

But now, when I try to use GoogleScraper it does not work : 

Traceback (most recent call last):
  File "~/.conda/envs/my_python_anaconda/bin/GoogleScraper", line 9, in <module>
    load_entry_point('GoogleScraper==0.1.37', 'console_scripts', 'GoogleScraper')()
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/setuptools-12.0.4-py3.4.egg/pkg_resources/__init__.py", line 519, in load_entry_point
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/setuptools-12.0.4-py3.4.egg/pkg_resources/__init__.py", line 2630, in load_entry_point
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/setuptools-12.0.4-py3.4.egg/pkg_resources/__init__.py", line 2310, in load
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/setuptools-12.0.4-py3.4.egg/pkg_resources/__init__.py", line 2316, in resolve
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/GoogleScraper/__init__.py", line 20, in <module>
    from GoogleScraper.core import scrape_with_config
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/GoogleScraper/core.py", line 13, in <module>
    from GoogleScraper.caching import fix_broken_cache_names, _caching_is_one_to_one, parse_all_cached_files, \
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/GoogleScraper/caching.py", line 16, in <module>
    from GoogleScraper.output_converter import store_serp_result
  File "~/.conda/envs/my_python_anaconda/lib/python3.4/site-packages/GoogleScraper/output_converter.py", line 19, in <module>
    csv_fieldnames = set(Link.__table__.columns._data.keys() + SERP.__table__.columns._data.keys()) - {'id', 'serp_id'}
TypeError: unsupported operand type(s) for +: 'list_iterator' and 'list_iterator'

Do you have any idea?

Thank you very much.

Thanks, PaulZ

**Comment by mhenes** [comment]
I get the same error.
