### ISSUE TITLE
"no available selenium webdriver" - but Selenium does work from terminal

### ISSUE THREAD

**Issue by Kr0nZ** [NikolaiT/GoogleScraper#111]
Im not sure whats going on here but when i tried the basic usage script from the example page, it results in the following error:

```
Exception in thread [yandex]SelScrape:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/demon/.virtualenvs/gscrape/lib/python3.4/site-packages/GoogleScraper/selenium_mode.py", line 581, in run
    exception_obj=SeleniumMisconfigurationError)
  File "/home/demon/.virtualenvs/gscrape/lib/python3.4/site-packages/GoogleScraper/log.py", line 32, in raise_or_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [yandex]SelScrape: Aborting due to no available selenium webdriver.
```

Looking into 'GoogleScraper/selenium_mode.py', it looks to be hanging when trying to acquire the webdriver.
_get_Chrome() function: 
```self.webdriver = webdriver.Chrome()```
It blocks until the above error is produced.

However, when i try the following from a terminal, selenium does start chromium as expected, so it looks like i do have the chromedriver, selenium, and chromium installed correctly, so not really sure what the problem is:
```
>>> from selenium import webdriver
>>> webdriver = webdriver.Chrome()
*** chromium window opens***
```

**Comment by Kr0nZ** [comment]
I found the problem, seems to be something with how selenium tries to run headless, in the selenium_mode.py file i commented out *** self._set_xvfb_display() *** from the run method and it is now running fine, to get back the headless functionality i just do the following from my script and its seems to be working, now to make something!!!! :P
```
from pyvirtualdisplay import Display
display = Display(visible=0, size=(800, 600))
display.start()
```

**Comment by rcompton** [comment]
+1

To get this to run in commandline mode I added your 3 pyvirtualdisplay lines to selenium_mode.py and commented out the xvfb line. Seems to work ok for now.
