### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by clarkk** [NikolaiT/GoogleScraper#143]
Install
```
apt-get install python-setuptools python-virtualenv
easy_install pip

virtualenv --python python3 env
source env/bin/activate
pip install git+git://github.com/NikolaiT/GoogleScraper/
```

Run
```
# GoogleScraper -h
-bash: GoogleScraper: command not found
```

**Comment by clarkk** [comment]
Ok..

Don't know what I did, but now I can run the command.. But get a stacktrace

```
(env)root@dyntest-athlon-3700-2gb ~ # python -V
Python 3.4.2
(env)root@dyntest-athlon-3700-2gb ~ # GoogleScraper -h
Traceback (most recent call last):
  File "/root/env/bin/GoogleScraper", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/root/env/lib/python3.4/site-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/root/env/lib/python3.4/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/root/env/lib/python3.4/site-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/root/env/lib/python3.4/site-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: aiohttp
```

**Comment by clarkk** [comment]
Here is the complete step by step installation

**Install Google Chrome**
```
wget -c wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && dpkg -i google-chrome-stable_current_amd64.deb
apt-get -f install
```

**Install Selenium**
```
apt-get install python-pip
pip install selenium
```

**GoogleScraper**
```
apt-get install python-dev python-virtualenv
virtualenv --python python3 env
source env/bin/activate
pip install GoogleScraper
```

**Run**
```
source env/bin/activate
GoogleScraper -h
```

**Comment by MichaelPavlov** [comment]
Same here, can't install

`http
Collecting aiohttp
  Using cached aiohttp-0.21.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KM5mst/aiohttp/setup.py", line 61, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.1+")
    RuntimeError: aiohttp requires Python 3.4.1+`

I have python 3.4.3+ and 3.5 installed

**Comment by MichaelPavlov** [comment]
Installed this with commands:
> git clone git://github.com/NikolaiT/GoogleScraper/
> sudo -H python3 setup.py install

**Comment by ycchuang** [comment]
Maybe you can check your version of python first.
sys.version_info

**Comment by 3ruce** [comment]
Following the instructions from @clarkk, I had a lot of similar errors on Ubuntu 14.04 but installing these packages first worked.

`sudo apt-get install python3.4-dev python-virtualenv build-essential python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev`

I also installed the Python 3.5 PPA from [here](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes) before I began. It seems to have worked!

Installing `zlib1g-dev` came from [this Stackoverflow question](http://stackoverflow.com/questions/34772030/lxml-error-command-x86-64-linux-gnu-gcc-failed-with-exit-status-1) and `libxml2-dev + libxslt1-dev` were from @NikolaiT via [this issue](https://github.com/NikolaiT/GoogleScraper/issues/41#issuecomment-67901822).
