### ISSUE TITLE
Unknown Proxy Error

### ISSUE THREAD

**Issue by michaeldg3** [NikolaiT/GoogleScraper#155]
Some proxies will work perfectly fine with the configuration I'm running but others randomly won't and return this as an error:

> 
Exception in thread [google]HttpScrape:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/GoogleScraper/http_mode.py", line 298, in run
    super().before_search()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/GoogleScraper/scraping.py", line 373, in before_search
    if not self.proxy_check(self.proxy):
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/GoogleScraper/http_mode.py", line 221, in proxy_check
    super().update_proxy_status(status, ipinfo, online)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/GoogleScraper/scraping.py", line 388, in update_proxy_status
    proxy = self.session.query(db_Proxy).filter(self.proxy.host == db_Proxy.ip).first()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2659, in first
    ret = list(self[0:1])
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2761, in __iter__
    return self._execute_and_instances(context)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2774, in _execute_and_instances
    close_with_result=True)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2765, in _connection_from_session
    **kw)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 893, in connection
    execution_options=execution_options)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 898, in _connection_for_bind
    engine, execution_options)
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 313, in _connection_for_bind
    self._assert_active()
  File "/home/ubuntu/workspace/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.IntegrityError) UNIQUE constraint failed: proxy.ip, proxy.port [SQL: 'UPDATE proxy SET ip=?, hostname=?, online=?, status=?, checked_at=?, city=?, region=?, country=?, loc=?, org=?, postal=? WHERE proxy.id = ?'] [parameters: ('104.197.238.78', '78.238.197.104.bc.googleusercontent.com', 1, 'Proxy is working.', '2016-05-28 06:51:53.871728', 'Mountain View', 'California', 'US', '37.4192,-122.0574', 'AS15169 Google Inc.', '94043', 110)]

I'm not sure what the problem is with some of these proxies but please help.

**Comment by michaeldg3** [comment]
> GoogleScraper --clean

This fixed it.
