### ISSUE TITLE
README.md examples have issues

### ISSUE THREAD

**Issue by lexsca** [NikolaiT/GoogleScraper#160]
The examples in the `README.md` have issues around the log level.  Example:

```
GoogleScraper -m http --keyword "apple" -v2
```

This generates the following Traceback:

``` python
Traceback (most recent call last):
  File "/Users/lscarisb/.venv/scratch/bin/GoogleScraper", line 11, in <module>
    sys.exit(main())
  File "/Users/lscarisb/.venv/scratch/lib/python3.5/site-packages/GoogleScraper/core.py", line 173, in main
    setup_logger(level=config.get('log_level').upper())
  File "/Users/lscarisb/.venv/scratch/lib/python3.5/site-packages/GoogleScraper/log.py", line 23, in setup_logger
    logger.setLevel(level)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 1255, in setLevel
    self.level = _checkLevel(level)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/logging/__init__.py", line 187, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: '2'
```

Looking at the source, it appears as though arguments to `-v` should correspond to syslog severity level strings, not integers.  Not sure whether the source or the documentation should change here.

**Comment by JanAhrend** [comment]
This hint on [stackoverflow](https://stackoverflow.com/questions/39296645/receiving-a-valueerror-unknown-level-when-running-googlescraper) worked for me: 
`GoogleScraper -m http --keyword "apple" -v INFO`
