### ISSUE TITLE
errors?

### ISSUE THREAD

**Issue by dodoaska** [NikolaiT/GoogleScraper#183]
(env) [root@b19s04 ~]# GoogleScraper -m http --keyword "apple" -v2
Traceback (most recent call last):
  File "/usr/src/env/bin/GoogleScraper", line 11, in <module>
    sys.exit(main())
  File "/usr/src/env/lib/python3.4/site-packages/GoogleScraper/core.py", line 173, in main
    setup_logger(level=config.get('log_level').upper())
  File "/usr/src/env/lib/python3.4/site-packages/GoogleScraper/log.py", line 23, in setup_logger
    logger.setLevel(level)
  File "/usr/lib64/python3.4/logging/__init__.py", line 1255, in setLevel
    self.level = _checkLevel(level)
  File "/usr/lib64/python3.4/logging/__init__.py", line 187, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: '2'

**Comment by mlifemaker** [comment]
don't use -v2 
just do this:
$GoogleScraper -m http --keyword "apple"
