### ISSUE TITLE
Issue with proxy file

### ISSUE THREAD

**Issue by lorenzoromani1983** [NikolaiT/GoogleScraper#208]
Hi.
I am not able to run the proxy file.
I have it formatted this way: 

Socks4	182.48.90.81:1080
Socks4	36.37.225.50:33012

it is a simple txt file with many rows
i get this error message:

Invalid proxy file. Should have the following format: {}'.format(parse_proxy_file.__doc__))
Exception: Invalid proxy file. Should have the following format: Parses a proxy file

please, help :)

**Comment by fassn** [comment]
This project hasn't  been updated for more than a year. Prefer using this project, developed from this one: https://github.com/fassn/SerpScrap (this is just a fork, I didn't started the project)

**Comment by lorenzoromani1983** [comment]
thanks.
but that, as far as i understand, needs to be used within code.
this is a "stand-alone" tool...which is easier for me (not a coder, not an expert at all).
did you manage to make the proxies work in http mode?
i need to get a json/csv of 700/800 kw from google.

**Comment by fassn** [comment]
Yes, I use proxies on the SerpScrap projet without problems

**Comment by lorenzoromani1983** [comment]
I am trying to use serpscrap. Thank you, it looks neat.
However, I can't save to csv, and I get this error:

Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\csv_writer.py", line 10, in write
    with open(file_name, 'w', encoding='utf-8', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'c:/.csv'
None
Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\csv_writer.py", line 10, in write
    with open(file_name, 'w', encoding='utf-8', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'c:/.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lorenzo\Desktop\scraper.txt", line 17, in <module>
    results = scrap.as_csv('c:/')
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\serpscrap.py", line 134, in as_csv
    writer.write(file_path + '.csv', self.results)
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\csv_writer.py", line 17, in write
    raise Exception
Exception

how to proceed??
tnx

**Comment by lorenzoromani1983** [comment]
THanks, it looks neat. However, I cant save to CSV:
how to proceed? this is the error i get:

Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\csv_writer.py", line 10, in write
    with open(file_name, 'w', encoding='utf-8', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'c:/.csv'
None
Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\csv_writer.py", line 10, in write
    with open(file_name, 'w', encoding='utf-8', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'c:/.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lorenzo\Desktop\scraper.txt", line 17, in <module>
    results = scrap.as_csv('c:/')
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\serpscrap.py", line 134, in as_csv
    writer.write(file_path + '.csv', self.results)
  File "C:\Users\Lorenzo\Anaconda\lib\site-packages\serpscrap\csv_writer.py", line 17, in write
    raise Exception
Exception

**Comment by ecoron** [comment]
hi,
* for question 1 can you please open an issue in the serpscrap project (https://github.com/ecoron/SerpScrap/issues)
* for question 2: yes most of free online proxies are banned or blocked by google
