### ISSUE TITLE
Problem intalling on GIT CMD Shell for Windows 10

### ISSUE THREAD

**Issue by arkochhar** [NikolaiT/GoogleScraper#211]
(googlescraper) C:\Users\arkoc\workspace\webenza_serp\GoogleScraper>pip install GoogleScraper
Collecting GoogleScraper
  Using cached https://files.pythonhosted.org/packages/51/e5/c60b0f6cb72b7faeb38da5171331450ab84d90e87224b442fe77817c69b8/GoogleScraper-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info\GoogleScraper.egg-info
    writing pip-egg-info\GoogleScraper.egg-info\PKG-INFO
    writing dependency_links to pip-egg-info\GoogleScraper.egg-info\dependency_links.txt
    writing entry points to pip-egg-info\GoogleScraper.egg-info\entry_points.txt
    writing requirements to pip-egg-info\GoogleScraper.egg-info\requires.txt
    writing top-level names to pip-egg-info\GoogleScraper.egg-info\top_level.txt
    writing manifest file 'pip-egg-info\GoogleScraper.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\arkoc\AppData\Local\Temp\pip-install-7yxf4e3n\GoogleScraper\setup.py", line 25, in <module>
        install_requires=requirements
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python36\Lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python36\Lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\program files\python36\Lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\command\egg_info.py", line 278, in run
        self.find_sources()
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\command\egg_info.py", line 293, in find_sources
        mm.run()
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\command\egg_info.py", line 524, in run
        self.add_defaults()
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\command\egg_info.py", line 560, in add_defaults
        sdist.add_defaults(self)
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\command\py36compat.py", line 34, in add_defaults
        self._add_defaults_python()
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\command\sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "c:\program files\python36\Lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "c:\program files\python36\Lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "c:\users\arkoc\envs\googlescraper\lib\site-packages\setuptools\command\build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "c:\program files\python36\Lib\distutils\command\build_py.py", line 55, in finalize_options
        self.package_dir[name] = convert_path(path)
      File "c:\program files\python36\Lib\distutils\util.py", line 127, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'examples/' cannot end with '/'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\arkoc\AppData\Local\Temp\pip-install-7yxf4e3n\GoogleScraper\

(googlescraper) C:\Users\arkoc\workspace\webenza_serp\GoogleScraper>

**Comment by NikolaiT** [comment]
There will be a new version on PIP. For now please install the latest version from github directly.
