### ISSUE TITLE
No working GoogleScraper instance

### ISSUE THREAD

**Issue by NikolaiT** [NikolaiT/GoogleScraper#25]
Sometimes I fuck up and I leave no working GoogleScraper instance online. For example right now GoogleScraper 0.1.3 doesn't work when installing from pip. Nor does the most recent version on Github work. So the users aren't happy.

If this happens and I overlook it, please shoot me short message in this thread and I will fix the issue.

Best regards

**Comment by adammonro55** [comment]
I tried installing with PIP and by downloading from hit and I keep getting the following error when runing GoogleScraper ( any command, even GoogleScraper -h) 
Traceback (most recent call last):
  File "/root/env/bin/GoogleScraper", line 9, in <module>
    load_entry_point('GoogleScraper==0.1.37', 'console_scripts', 'GoogleScraper')()
  File "/root/env/lib/python3.2/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/root/env/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/root/env/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/root/env/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/env/lib/python3.2/site-packages/GoogleScraper-0.1.37-py3.2.egg/GoogleScraper/__init__.py", line 20, in <module>
    from GoogleScraper.core import scrape_with_config
  File "/root/env/lib/python3.2/site-packages/GoogleScraper-0.1.37-py3.2.egg/GoogleScraper/core.py", line 18, in <module>
    from GoogleScraper.scraping import ScrapeWorkerFactory
  File "/root/env/lib/python3.2/site-packages/GoogleScraper-0.1.37-py3.2.egg/GoogleScraper/scraping.py", line 403, in <module>
    from GoogleScraper.http_mode import HttpScrape
  File "/root/env/lib/python3.2/site-packages/GoogleScraper-0.1.37-py3.2.egg/GoogleScraper/http_mode.py", line 123, in <module>
    class HttpScrape(SearchEngineScrape, threading.Timer):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

**Comment by NikolaiT** [comment]
Python 3.2 is not offically supported. Use the latest version of python.
