### ISSUE TITLE
not pretty logger error 

### ISSUE THREAD

**Issue by sbmzhcn** [NikolaiT/GoogleScraper#49]
```
C:\Python33\python.exe D:/workfiles/PythonScript/GoogleScraper-master/usage.py
2015-01-05 17:27:15,699 - GoogleScraper - INFO - 0 cache files found in .scrapecache/
2015-01-05 17:27:15,699 - GoogleScraper - INFO - 0/5 keywords have been cached and are ready to get parsed. 5 remain to get scraped.
2015-01-05 17:27:15,749 - GoogleScraper - INFO - Going to scrape 5 keywords with 1 proxies by using 3 threads.
2015-01-05 17:27:15,816 - GoogleScraper - INFO - [+] HttpScrape[localhost][search-type:normal] created using the search engine google. Number of keywords to scrape=1, using proxy=None, number of pages per keyword=2
2015-01-05 17:27:15,816 - GoogleScraper - INFO - [+] HttpScrape[localhost][search-type:normal] created using the search engine google. Number of keywords to scrape=2, using proxy=None, number of pages per keyword=2
2015-01-05 17:27:15,816 - GoogleScraper - INFO - [+] HttpScrape[localhost][search-type:normal] created using the search engine google. Number of keywords to scrape=2, using proxy=None, number of pages per keyword=2
2015-01-05 17:27:23,844 - GoogleScraper - ERROR - Connection timeout (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000042907B8>, 'Connection to www.google.com timed out. (connect timeout=5)')
2015-01-05 17:27:23,844 - GoogleScraper - ERROR - Connection timeout (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000429B8D0>, 'Connection to www.google.com timed out. (connect timeout=5)')
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connection.py", line 136, in connect
    timeout=self.timeout,
  File "C:\Python33\lib\socket.py", line 435, in create_connection
    raise err
  File "C:\Python33\lib\socket.py", line 426, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\adapters.py", line 330, in send
    timeout=timeout
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python33\lib\http\client.py", line 1061, in request
    self._send_request(method, url, body, headers)
  File "C:\Python33\lib\http\client.py", line 1099, in _send_request
    self.endheaders(body)
  File "C:\Python33\lib\http\client.py", line 1057, in endheaders
    self._send_output(message_body)
  File "C:\Python33\lib\http\client.py", line 902, in _send_output
    self.send(msg)
  File "C:\Python33\lib\http\client.py", line 840, in send
    self.connect()
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connection.py", line 141, in connect
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000429B8D0>, 'Connection to www.google.com timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\threading.py", line 637, in _bootstrap_inner
    self.run()
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 609, in run
    SearchEngineScrape.blocking_search(self, self.search, *args, **kwargs)
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 228, in blocking_search
    callback(*args, **kwargs)
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 595, in search
    raise te
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 586, in search
    params=self.search_params, timeout=5)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\adapters.py", line 387, in send
    raise Timeout(e)
requests.exceptions.Timeout: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000429B8D0>, 'Connection to www.google.com timed out. (connect timeout=5)')

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connection.py", line 136, in connect
    timeout=self.timeout,
  File "C:\Python33\lib\socket.py", line 435, in create_connection
    raise err
  File "C:\Python33\lib\socket.py", line 426, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\adapters.py", line 330, in send
    timeout=timeout
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python33\lib\http\client.py", line 1061, in request
    self._send_request(method, url, body, headers)
  File "C:\Python33\lib\http\client.py", line 1099, in _send_request
    self.endheaders(body)
  File "C:\Python33\lib\http\client.py", line 1057, in endheaders
    self._send_output(message_body)
  File "C:\Python33\lib\http\client.py", line 902, in _send_output
    self.send(msg)
  File "C:\Python33\lib\http\client.py", line 840, in send
    self.connect()
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connection.py", line 141, in connect
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000042907B8>, 'Connection to www.google.com timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\threading.py", line 637, in _bootstrap_inner
    self.run()
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 609, in run
    SearchEngineScrape.blocking_search(self, self.search, *args, **kwargs)
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 228, in blocking_search
    callback(*args, **kwargs)
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 595, in search
    raise te
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 586, in search
    params=self.search_params, timeout=5)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\adapters.py", line 387, in send
    raise Timeout(e)
requests.exceptions.Timeout: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000042907B8>, 'Connection to www.google.com timed out. (connect timeout=5)')

2015-01-05 17:27:24,821 - GoogleScraper - ERROR - Connection timeout (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000042A8BA8>, 'Connection to www.google.com timed out. (connect timeout=5)')
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connection.py", line 136, in connect
    timeout=self.timeout,
  File "C:\Python33\lib\socket.py", line 435, in create_connection
    raise err
  File "C:\Python33\lib\socket.py", line 426, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\adapters.py", line 330, in send
    timeout=timeout
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py", line 480, in urlopen
    body=body, headers=headers)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connectionpool.py", line 285, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python33\lib\http\client.py", line 1061, in request
    self._send_request(method, url, body, headers)
  File "C:\Python33\lib\http\client.py", line 1099, in _send_request
    self.endheaders(body)
  File "C:\Python33\lib\http\client.py", line 1057, in endheaders
    self._send_output(message_body)
  File "C:\Python33\lib\http\client.py", line 902, in _send_output
    self.send(msg)
  File "C:\Python33\lib\http\client.py", line 840, in send
    self.connect()
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\packages\urllib3\connection.py", line 141, in connect
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000042A8BA8>, 'Connection to www.google.com timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python33\lib\threading.py", line 637, in _bootstrap_inner
    self.run()
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 609, in run
    SearchEngineScrape.blocking_search(self, self.search, *args, **kwargs)
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 228, in blocking_search
    callback(*args, **kwargs)
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 595, in search
    raise te
  File "D:\workfiles\PythonScript\GoogleScraper-master\GoogleScraper\scraping.py", line 586, in search
    params=self.search_params, timeout=5)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\api.py", line 55, in get
    return request('get', url, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\sessions.py", line 383, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\sessions.py", line 486, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python33\lib\site-packages\requests-2.2.1-py3.3.egg\requests\adapters.py", line 387, in send
    raise Timeout(e)
requests.exceptions.Timeout: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000042A8BA8>, 'Connection to www.google.com timed out. (connect timeout=5)')


```

i use googlescraper scrape 5 keyword with non proxy, so the 5 keyword is all failed. but the error infomartion is not suitable for reading, and the  Program will get stuck。

in this code, super().after_search(request.text) will not run:
```
        except self.requests.ConnectionError as ce:
            logger.error('Network problem occurred {}'.format(ce))
            raise ce
        except self.requests.Timeout as te:
            logger.error('Connection timeout {}'.format(te))
            raise te

        if not request.ok:
            logger.error('HTTP Error: {}'.format(request.status_code))
            self.handle_request_denied(request.status_code)
            return False
!!!!  # is have except or return false, below code is never run
        super().after_search(request.text)
```

so these code is never run : 
```
    def after_search(self, html):
        """Store the results and parse em.

        Notify the progress queue if necessary.

        Args:
            html: The scraped html.
        """
        self.parser.parse(html)
        self.store()
        if self.progress_queue:
            self.progress_queue.put(1)
        self.cache_results()
        self.search_number += 1
```

```
progress_thread.join()
```
will stop.

the program will never exit.

**Comment by NikolaiT** [comment]
Fixed.
