### ISSUE TITLE
'GoogleParser' object has no attribute 'links'

### ISSUE THREAD

**Issue by aidiss** [NikolaiT/GoogleScraper#64]
Is this a bug or am I doing something wrong?

```

D:\scraping\googlescrap>GoogleScraper -m http --keyword "apple" --output-format json --output-filename output -v2
2015-01-13 08:47:24,095 - GoogleScraper - INFO - 0 cache files found in .scrapecache/
2015-01-13 08:47:24,096 - GoogleScraper - INFO - 0/1 keywords have been cached and are ready to get parsed. 1 remain to get scraped.
2015-01-13 08:47:24,121 - GoogleScraper - INFO - Going to scrape 1 keywords with 1 proxies by using 1 threads.
2015-01-13 08:47:24,230 - GoogleScraper - INFO - [+] HttpScrape[localhost][search-type:normal][https://www.google.com/search?] using search engine "google". Num keywords =1, num pages for keyword=1
2015-01-13 08:47:29,230 - GoogleScraper - INFO - [Thread-2][localhost][google]Keyword: "apple" with 1 pages, slept 5 seconds before scraping. 1/1 already scraped.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\c\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\c\lib\site-packages\GoogleScraper\http.py", line 290, in run
    SearchEngineScrape.blocking_search(self, self.search, *args, **kwargs)
  File "C:\c\lib\site-packages\GoogleScraper\scraping.py", line 271, in blocking_search
    if not callback(*args, **kwargs):
  File "C:\c\lib\site-packages\GoogleScraper\http.py", line 279, in search
    super().after_search()
  File "C:\c\lib\site-packages\GoogleScraper\scraping.py", line 399, in after_search
    if not self.store():
  File "C:\c\lib\site-packages\GoogleScraper\scraping.py", line 333, in store
    store_serp_result(dict_from_scraping_object(self), self.parser)
  File "C:\c\lib\site-packages\GoogleScraper\output_converter.py", line 74, in store_serp_result
    obj['results'] = results()
  File "C:\c\lib\site-packages\GoogleScraper\output_converter.py", line 69, in results
    for link in serp.links:
AttributeError: 'GoogleParser' object has no attribute 'links'

```

**Comment by NikolaiT** [comment]
This is a bug.

**Comment by aidiss** [comment]
What is the cause of this problem? Is ir related with output type?

**Comment by NikolaiT** [comment]
Fixed it. Sorry for the inconvenience :/
