### ISSUE TITLE
TypeError: get_session() got an unexpected keyword argument 'create'

### ISSUE THREAD

**Issue by aidiss** [NikolaiT/GoogleScraper#65]
D:\scraping\googlescrap>GoogleScraper --shell
Traceback (most recent call last):
  File "C:\c\Scripts\GoogleScraper-script.py", line 9, in <module>
    load_entry_point('GoogleScraper==0.1.17', 'console_scripts', 'GoogleScraper')()
  File "C:\c\lib\site-packages\GoogleScraper\core.py", line 206, in main
    Session = get_session(scoped=False, create=False)
TypeError: get_session() got an unexpected keyword argument 'create'

**Comment by NikolaiT** [comment]
I need tests :/

Please install from the github repo, it should work.
