### ISSUE TITLE
How to detect if the scrapper is showing hits for original query or the modified query (by google)?

### ISSUE THREAD

**Issue by p6jain** [NikolaiT/GoogleScraper#67]
For queries like -
'"be dealt and be evaluated"'
google says: No results found for "be dealt and be evaluated".
but it shows results for a modified query: Results for be dealt and be evaluated (without quotes)

In such cases GoogleScrapper outputs the number of hits from the modified query.
Is there a way I can find if the hits are for the original query or the modified version?

**Comment by NikolaiT** [comment]
No you couldn't, but I just added this right now. Now any SERP object has a property **effective_query** which is set to the search query that was used instead of your original search string. If this attribute is empty, then or course your original search had some results.

**Comment by p6jain** [comment]
Now I got this error:
sqlite3.OperationalError: table serp has no column named effective_query

Details:
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table serp has no column named effective_query

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/path_to_file/env/lib/python3.4/site-packages/GoogleScraper-0.1.18-py3.4.egg/GoogleScraper/selenium_mode.py", line 431, in run
    self.search()
  File "/path_to_file/env/lib/python3.4/site-packages/GoogleScraper-0.1.18-py3.4.egg/GoogleScraper/selenium_mode.py", line 385, in search
    super().after_search()
  File "/path_to_file/env/lib/python3.4/site-packages/GoogleScraper-0.1.18-py3.4.egg/GoogleScraper/scraping.py", line 400, in after_search
    if not self.store():
  File "/path_to_file/env/lib/python3.4/site-packages/GoogleScraper-0.1.18-py3.4.egg/GoogleScraper/scraping.py", line 330, in store
    self.session.commit()
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 65, in save_obj
    mapper, table, insert)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 602, in _emit_insert_statements
    execute(statement, params)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (OperationalError) table serp has no column named effective_query 'INSERT INTO serp (search_engine_name, scrapemethod, page_number, requested_at, requested_by, num_results, "query", effective_query, num_results_for_keyword) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' ('google', 'selenium', 1, '2015-01-15 05:12:19.834026', 'localhost', 6, '"query_by_me"', '"query_by_me"', 'About 8,67,00,000 results (0.38 seconds)\xa0')

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/path_to_file/env/lib/python3.4/site-packages/GoogleScraper-0.1.18-py3.4.egg/GoogleScraper/core.py", line 55, in scrape_with_config
    return main(return_results=True, parse_cmd_line=False, **kwargs)
  File "/path_to_file/env/lib/python3.4/site-packages/GoogleScraper-0.1.18-py3.4.egg/GoogleScraper/core.py", line 421, in main
    session.commit()
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 375, in commit
    self._assert_active(prepared_ok=True)
  File "/path_to_file/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (OperationalError) table serp has no column named effective_query 'INSERT INTO serp (search_engine_name, scrapemethod, page_number, requested_at, requested_by, num_results, "query", effective_query, num_results_for_keyword) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' ('google', 'selenium', 1, '2015-01-15 05:12:19.834026', 'localhost', 6, '"query_by_me"', '"query_by_me"', 'About 8,67,00,000 results (0.38 seconds)\xa0')

**Comment by NikolaiT** [comment]
Try this:

```GoogleScraper --clean```

and then try your search again.

**Comment by p6jain** [comment]
ok. Thanks :+1:

**Comment by NikolaiT** [comment]
Your welcome. And stay tuned, GoogleScraper is under heavy development and it's functionality will get better very soon...
