### ISSUE TITLE
Error: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mtmarsh2** [NikolaiT/GoogleScraper#70]
Here's the full traceback, has anyone gotten these?

No handlers could be found for logger "GoogleScraper"
Traceback (most recent call last):
  File "/usr/local/bin/GoogleScraper", line 9, in <module>
    load_entry_point('GoogleScraper==0.1.18', 'console_scripts', 'GoogleScraper')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/GoogleScraper/__init__.py", line 20, in <module>
    from GoogleScraper.core import scrape_with_config
  File "/usr/local/lib/python2.7/dist-packages/GoogleScraper/core.py", line 150
    print(self.progress_fmt.format(self.num_already_processed, self.num_keywords), end='\r')

**Comment by NikolaiT** [comment]
GoogleScraper is written in Python3. Try to install with Python3. Sometimes you need to install like this

```
sudo pip**3** GoogleScraper
```

instead of 

```
sudo pip GoogleScraper
```

**Comment by mtmarsh2** [comment]
I changed to python 3, and checked the version to make sure, but now I'm getting this error after running pip3 install Google Scraper:

File "/usr/bin/pip3", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 227, in main
    cmd_name, cmd_args = parseopts(initial_args)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 206, in parseopts
    cmd_args.remove(args_else[0].lower())
ValueError: list.remove(x): x not in list
