### ISSUE TITLE
GoogleScraper.scraping.SeleniumMisconfigurationError: Aborting due to no available selenium webdrive

### ISSUE THREAD

**Issue by marcoippolito** [NikolaiT/GoogleScraper#74]
Hi Nikolai,

in my Ubuntu 14.04.01 Server Edition I installed:
GoogleScraper
chromium-chromedriver - WebDriver driver for the Chromium Browser
chromium-chromedriver-dbg - chromium-chromedriver debug symbols

I also downloaded from http://chromedriver.storage.googleapis.com/index.html?path=2.13/ and installed chromedriver.
As suggested https://code.google.com/p/selenium/wiki/ChromeDriver, I symlinked with /usr/bin:
:/usr/bin$ ls -lah chromedriver
lrwxrwxrwx 1 root root 24 gen 21 12:06 chromedriver -> /home/marco/chromedriver

But when running the direct command line (https://github.com/NikolaiT/GoogleScraper):
marco@pc:~/crawlscrape$ GoogleScraper --keyword-file keywords.txt --search-engine bing --num-pages-for-keyword 3 --scrapemethod selenium
2015-01-21 15:07:45,339 - GoogleScraper - INFO - 0 cache files found in .scrapecache/
2015-01-21 15:07:45,339 - GoogleScraper - INFO - 0/11 keywords have been cached and are ready to get parsed. 11 remain to get scraped.
2015-01-21 15:07:45,624 - GoogleScraper - INFO - Going to scrape 10 keywords with 1 proxies by using 1 threads.
2015-01-21 15:07:45,624 - GoogleScraper - INFO - [+] SelScrape[localhost][search-type:normal][http://www.bing.com/search?] using search engine "bing". Num keywords=10, num pages for keyword=3
2015-01-21 15:07:45,640 - GoogleScraper - ERROR - Message: ChromeDriver executable needs to be available in the path. Please download from http://chromedriver.storage.googleapis.com/index.html and read up at http://code.google.com/p/selenium/wiki/ChromeDriver

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/GoogleScraper/selenium_mode.py", line 419, in run
    raise SeleniumMisconfigurationError('Aborting due to no available selenium webdriver.')
GoogleScraper.scraping.SeleniumMisconfigurationError: Aborting due to no available selenium webdriver.

What do I have to do in order to make it work?
Looking forward to your help.
Marco

**Comment by marcoippolito** [comment]
After removing and re-installing the driver:
marco@pc:/usr/bin$ ls -lh chromedriver
lrwxrwxrwx 1 root root 24 gen 26 10:55 chromedriver -> /home/marco/chromedriver

marco@pc:~/crawlscrape$ chromedriver –version
ChromeDriver 2.13.307649 (bf55b442bb6b5c923249dd7870d6a107678bfbb6)

it seems now correctly installed
But when trying to execute the command from the command line:

marco@pc:~/crawlscrape$ GoogleScraper –keyword-file keywords.txt –search-engine bing –num-pages-for-keyword 3 –scrapemethod selenium
2015-01-26 10:58:50,071 – GoogleScraper – INFO – 0 cache files found in .scrapecache/
2015-01-26 10:58:50,071 – GoogleScraper – INFO – 0/11 keywords have been cached and are ready to get parsed. 11 remain to get scraped.
2015-01-26 10:58:50,335 – GoogleScraper – INFO – Going to scrape 10 keywords with 1 proxies by using 1 threads.
2015-01-26 10:58:50,335 – GoogleScraper – INFO – [+] SelScrape[localhost][search-type:normal][http://www.bing.com/search?] using search engine “bing”. Num keywords=10, num pages for keyword=3
2015-01-26 10:59:51,404 – GoogleScraper – ERROR – Message: unknown error: Chrome failed to start: exited abnormally
(Driver info: chromedriver=2.13.307649 (bf55b442bb6b5c923249dd7870d6a107678bfbb6),platform=Linux 3.13.0-32-generic x86_64)

Exception in thread Thread-2:
Traceback (most recent call last):
File “/usr/lib/python3.4/threading.py”, line 920, in _bootstrap_inner
self.run()
File “/usr/local/lib/python3.4/dist-packages/GoogleScraper/selenium_mode.py”, line 419, in run
raise SeleniumMisconfigurationError(‘Aborting due to no available selenium webdriver.’)
GoogleScraper.scraping.SeleniumMisconfigurationError: Aborting due to no available selenium webdriver.

What do I have to do now?
Looking forward to your kind and patient help.
Marco

**Comment by stasmix** [comment]
I experience the same problem with multiple sequential queries: it works OK at the beginning but after a certain number of queries it raises SeleniumMisconfigurationError(‘Aborting due to no available selenium webdriver.’)

**Comment by DharmeshPandav** [comment]
any luck ?

**Comment by hojene007** [comment]
having the same problem, would be great to know a fix

**Comment by hojene007** [comment]
short term solution - close re-open python...
