### ISSUE TITLE
AttributeError: 'SelScrape' object has no attribute 'webdriver'

### ISSUE THREAD

**Issue by marcoippolito** [NikolaiT/GoogleScraper#78]
Running the example in here: https://github.com/NikolaiT/GoogleScraper 
GoogleScraper -m selenium --keyword "apple" -v2
2015-02-02 16:09:11,907 - GoogleScraper - INFO - 0 cache files found in .scrapecache/
2015-02-02 16:09:11,907 - GoogleScraper - INFO - 0/1 objects have been read from the cache. 1 remain to get scraped.
2015-02-02 16:09:12,022 - GoogleScraper - INFO - Going to scrape 1 keywords with 1 proxies by using 1 threads.
2015-02-02 16:09:12,024 - GoogleScraper - INFO - [+] SelScrape[localhost][search-type:normal][https://www.google.com/search?] using search engine "google". Num keywords=1, num pages for keyword=[1]
2015-02-02 16:10:13,055 - GoogleScraper - ERROR - Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.13.307649 (bf55b442bb6b5c923249dd7870d6a107678bfbb6),platform=Linux 3.13.0-32-generic x86_64)

2015-02-02 16:10:13,056 - GoogleScraper - WARNING - [google]SelScrape: Aborting due to no available selenium webdriver.
Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/marco/crawlscrape/env/lib/python3.4/site-packages/GoogleScraper/selenium_mode.py", line 497, in run
    self.webdriver.set_window_size(400, 400)
AttributeError: 'SelScrape' object has no attribute 'webdriver'

**Comment by NikolaiT** [comment]
Install chrome driver. See in the readme of GoogleScraper for installation.

Regards

**Comment by marcoippolito** [comment]
Hi Nikolai,
being stubborn, I tried again:

~/crawlscrape$ virtualenv --python python3 env
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in env/bin/python3
Not overwriting existing python script env/bin/python (you must use
env/bin/python3)
Installing setuptools, pip...done.
marco@pc:~/crawlscrape$ source env/bin/activate
(env)marco@pc:~/crawlscrape$ pip install GoogleScraper
Requirement already satisfied (use --upgrade to upgrade): GoogleScraper in
./env/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): lxml in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already satisfied (use --upgrade to upgrade): selenium in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already satisfied (use --upgrade to upgrade): cssselect in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already satisfied (use --upgrade to upgrade): requests in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already satisfied (use --upgrade to upgrade): PyMySql in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already satisfied (use --upgrade to upgrade): aiohttp in
./env/lib/python3.4/site-packages (from GoogleScraper)
Cleaning up...
(env)marco@pc:~/crawlscrape$ time ./google_scraper_example.py
Usage: ./google_scraper_example.py [basic|image-search]

real    0m0.709s
user    0m0.223s
sys     0m0.019s
(env)marco@pc:~/crawlscrape$ time ./google_scraper_example.py 'basic'
2015-02-21 13:06:43,953 - GoogleScraper - INFO - Going to scrape 1 keywords
with 1 proxies by using 1 threads.
2015-02-21 13:06:43,953 - GoogleScraper - INFO - [+]
SelScrape[localhost][search-type:normal][http://yandex.ru/yandsearch?]
using search engine "yandex". Num keywords=1, num pages for keyword=1
2015-02-21 13:07:45,055 - GoogleScraper - ERROR - Message: unknown error:
Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.13.307649
(bf55b442bb6b5c923249dd7870d6a107678bfbb6),platform=Linux 3.13.0-32-generic
x86_64)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File
"/usr/local/lib/python3.4/dist-packages/GoogleScraper/selenium_mode.py",
line 419, in run
    raise SeleniumMisconfigurationError('Aborting due to no available
selenium webdriver.')
GoogleScraper.scraping.SeleniumMisconfigurationError: Aborting due to no
available selenium webdriver.


So...
I followed the indications here:https://github.com/NikolaiT/GoogleScraper
during installation it says: "Requirement already satisfied" (second trial)
but when executing: "GoogleScraper.scraping.SeleniumMisconfigurationError:
Aborting due to no available selenium webdriver."

I also upgraded GoogleScraper:
(env)marco@pc:~/crawlscrape$  pip install --upgrade GoogleScraper
Downloading/unpacking GoogleScraper from
https://pypi.python.org/packages/source/G/GoogleScraper/GoogleScraper-0.1.36.tar.gz#md5=5a48b02dd0b3610d2412c997a71047b5
  Downloading GoogleScraper-0.1.36.tar.gz (74kB): 74kB downloaded
  Running setup.py
(path:/home/marco/crawlscrape/env/build/GoogleScraper/setup.py) egg_info
for package GoogleScraper

    file usage.py (for module usage) not found
Downloading/unpacking lxml from
https://pypi.python.org/packages/source/l/lxml/lxml-3.4.2.tar.gz#md5=429e5e771c4be0798923c04cb9739b4e
(from GoogleScraper)
  Downloading lxml-3.4.2.tar.gz (3.5MB): 3.5MB downloaded
  Running setup.py (path:/home/marco/crawlscrape/env/build/lxml/setup.py)
egg_info for package lxml
    Building lxml version 3.4.2.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown
distribution option: 'bugtrack_url'
      warnings.warn(msg)

    warning: no previously-included files found matching '*.py'
Requirement already up-to-date: selenium in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already up-to-date: cssselect in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already up-to-date: requests in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already up-to-date: PyMySql in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already up-to-date: sqlalchemy in
./env/lib/python3.4/site-packages (from GoogleScraper)
Requirement already up-to-date: aiohttp in
./env/lib/python3.4/site-packages (from GoogleScraper)
Installing collected packages: GoogleScraper, lxml
  Found existing installation: GoogleScraper 0.1.26
    Uninstalling GoogleScraper:
      Successfully uninstalled GoogleScraper
  Running setup.py install for GoogleScraper
    file usage.py (for module usage) not found
    file usage.py (for module usage) not found

    file usage.py (for module usage) not found
    Installing GoogleScraper script to /home/marco/crawlscrape/env/bin
    file usage.py (for module usage) not found
  Found existing installation: lxml 3.4.1
    Uninstalling lxml:
      Successfully uninstalled lxml
  Running setup.py install for lxml
    Building lxml version 3.4.2.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    building 'lxml.etree' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/libxml2
-I/home/marco/crawlscrape/env/build/lxml/src/lxml/includes
-I/usr/include/python3.4m -I/home/marco/crawlscrape/env/include/python3.4m
-c src/lxml/lxml.etree.c -o
build/temp.linux-x86_64-3.4/src/lxml/lxml.etree.o -w
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions
-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro
-g -fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2
build/temp.linux-x86_64-3.4/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz
-lm -o build/lib.linux-x86_64-3.4/lxml/etree.cpython-34m.so
    building 'lxml.objectify' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall
-Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/libxml2
-I/home/marco/crawlscrape/env/build/lxml/src/lxml/includes
-I/usr/include/python3.4m -I/home/marco/crawlscrape/env/include/python3.4m
-c src/lxml/lxml.objectify.c -o
build/temp.linux-x86_64-3.4/src/lxml/lxml.objectify.o -w
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions
-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro
-g -fstack-protector --param=ssp-buffer-size=4 -Wformat
-Werror=format-security -D_FORTIFY_SOURCE=2
build/temp.linux-x86_64-3.4/src/lxml/lxml.objectify.o -lxslt -lexslt -lxml2
-lz -lm -o build/lib.linux-x86_64-3.4/lxml/objectify.cpython-34m.so
    /usr/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown
distribution option: 'bugtrack_url'
      warnings.warn(msg)

Successfully installed GoogleScraper lxml
Cleaning up...

but again executing:
(env)marco@pc:~/crawlscrape$ time ./google_scraper_example.py 'basic'
2015-02-21 13:15:18,117 - GoogleScraper - INFO - Going to scrape 1 keywords
with 1 proxies by using 1 threads.
2015-02-21 13:15:18,117 - GoogleScraper - INFO - [+]
SelScrape[localhost][search-type:normal][http://yandex.ru/yandsearch?]
using search engine "yandex". Num keywords=1, num pages for keyword=1
2015-02-21 13:16:19,182 - GoogleScraper - ERROR - Message: unknown error:
Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.13.307649
(bf55b442bb6b5c923249dd7870d6a107678bfbb6),platform=Linux 3.13.0-32-generic
x86_64)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File
"/usr/local/lib/python3.4/dist-packages/GoogleScraper/selenium_mode.py",
line 419, in run
    raise SeleniumMisconfigurationError('Aborting due to no available
selenium webdriver.')
GoogleScraper.scraping.SeleniumMisconfigurationError: Aborting due to no
available selenium webdriver.


real    1m1.514s
user    0m0.911s
sys     0m0.338s

So..any more specific options?
Looking forward to your kind help.

Marco

2015-02-04 19:08 GMT+01:00 NikolaiT <notifications@github.com>:

**Comment by stasmix** [comment]
I experience the same problem with multiple sequential queries: it works OK at the beginning but after a certain number of queries it raises SeleniumMisconfigurationError(‘Aborting due to no available selenium webdriver.’) Maybe OS issue, dunno (Win8.1)

 1 proxies by using 1 threads.
2015-02-25 19:51:00,560 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
"Asian Civilisations Museum" AND Singapore  :  About 4,140,000 results (0.19 sec
onds) 
"Asian Civilisations Museum" AND Singapore  :  4140000
2015-02-25 19:51:11,437 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:11,439 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
"River Safari" AND Singapore  :  About 3,660,000 results (0.18 seconds) 
"River Safari" AND Singapore  :  3660000
2015-02-25 19:51:22,962 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:22,963 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
"Jurong BirdPark" AND Singapore  :  About 3,810,000 results (0.37 seconds) 
"Jurong BirdPark" AND Singapore  :  3810000
2015-02-25 19:51:36,583 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:36,584 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:36,585 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Jurong BirdPark" AND Singapore  :  About 3,810,000 results (0.37 seconds) 
"The Peranakan Museum" AND Singapore  :  3810000
2015-02-25 19:51:36,624 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:36,625 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:36,626 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Jurong BirdPark" AND Singapore  :  About 3,810,000 results (0.37 seconds) 
"Singapore Art Museum" AND Singapore  :  3810000
2015-02-25 19:51:36,668 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:36,669 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:36,670 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Jurong BirdPark" AND Singapore  :  About 3,810,000 results (0.37 seconds) 
"Singapore Science Centre" AND Singapore  :  3810000
2015-02-25 19:51:36,708 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:36,709 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"Singapore Zoological Gardens" AND Singapore  :  58700
2015-02-25 19:51:49,675 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:49,676 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:49,678 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"Sentosa" AND Singapore  :  58700
2015-02-25 19:51:49,936 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:49,938 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:49,939 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"Night Safari" AND Singapore  :  58700
2015-02-25 19:51:50,025 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:50,026 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:50,027 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"Chinese/Japanese Gardens" AND Singapore  :  58700
2015-02-25 19:51:50,100 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:50,101 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:50,102 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"National Museum of Singapore" AND Singapore  :  58700
2015-02-25 19:51:50,487 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:50,489 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:50,490 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"Gardens by the Bay" AND Singapore  :  58700
2015-02-25 19:51:50,600 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:50,601 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:50,602 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"Singapore Philatelic Museum" AND Singapore  :  58700
2015-02-25 19:51:50,700 - GoogleScraper - INFO - Going to scrape 1 keywords with
 1 proxies by using 1 threads.
2015-02-25 19:51:50,701 - GoogleScraper - INFO - [+] SelScrape[localhost][search
-type:normal][https://www.google.com/search?] using search engine "google". Num
keywords=1, num pages for keyword=[1]
2015-02-25 19:51:50,702 - GoogleScraper - ERROR - Message: ChromeDriver executab
le needs to be available in the path. Please download from http://chromedriver.s
torage.googleapis.com/index.html and read up at http://code.google.com/p/seleniu
m/wiki/ChromeDriver

Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\GoogleScraper\selenium_mode.py", line 499,
 in run
    raise_or_log('{}: Aborting due to no available selenium webdriver.'.format(s
elf.name), exception_obj=SeleniumMisconfigurationError)
  File "C:\Python34\lib\site-packages\GoogleScraper\log.py", line 30, in raise_o
r_log
    raise exception_obj(msg)
GoogleScraper.scraping.SeleniumMisconfigurationError: [google]SelScrape: Abortin
g due to no available selenium webdriver.

"Singapore Zoological Gardens" AND Singapore  :  About 58,700 results (0.17 seco
nds) 
"Singapore Discovery Centre" AND Singapore  :  58700
