### ISSUE TITLE
Aborting due to no available selenium webdriver. but during installation Requirement already up-to-date: selenium in ./env/lib/python3.4/site-packages (from GoogleScraper)

### ISSUE THREAD

**Issue by marcoippolito** [NikolaiT/GoogleScraper#86]
Hi Nikolai,
this time selenium seems correctly working, but GoogleScraper doesn't.... :

python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> import os
>>> from pyvirtualdisplay import Display
>>> display = Display(visible=0, size=(800, 600))
>>> display.start()
<Display cmd_param=['Xvfb', '-br', '-screen', '0', '800x600x24', ':1079'] alias={alias} cmd=['Xvfb', '-br', '-screen', '0', '800x600x24', ':1079'] ({scmd}) oserror=None returncode=None stdout="None" stderr="None" timeout=False>
>>> d = webdriver.Chrome()
>>> d.get("http://www.google.com")
>>> d.title
'Google'
>>>

./google_scraper_example.py 'basic'
2015-02-24 07:39:06,660 - GoogleScraper - INFO - Going to scrape 1 keywords with 1 proxies by using 1 threads.
2015-02-24 07:39:06,661 - GoogleScraper - INFO - [+] SelScrape[localhost][search-type:normal][http://yandex.ru/yandsearch?] using search engine "yandex". Num keywords=1, num pages for keyword=1
2015-02-24 07:40:07,684 - GoogleScraper - ERROR - Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 3.13.0-32-generic x86_64)

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/dist-packages/GoogleScraper/selenium_mode.py", line 419, in run
    raise SeleniumMisconfigurationError('Aborting due to no available selenium webdriver.')
GoogleScraper.scraping.SeleniumMisconfigurationError: Aborting due to no available selenium webdriver.

Looking forward to your kind help.
Marco

**Comment by marcoippolito** [comment]
solved.

**Comment by javierlores** [comment]
What was your solution? I'm having the same problem.

**Comment by frandres** [comment]
Hi. I'm having the same issue. I can use chromedriver from a python console but using GoogleScrapper fails. I get the exact same message.

Did anyone solve this?

**Comment by frandres** [comment]
Well if this of help to anyone, I think I solved this by commenting this line:

self._set_xvfb_display() 

in the file 'GoogleScraper/selenium_mode.py'

Doing that and updating Google Chrome seemed to fix it. I'm using ChromeDriver 2.15.322448

**Comment by jamesspittal** [comment]
Good find.

**Comment by javierlores** [comment]
Awesome work! Thanks so much!

**Comment by jamesspittal** [comment]
Tested this but I'm still having troubles:

````
2015-04-28 10:30:00,994 - GoogleScraper - INFO - [+] SelScrape[localhost][search-type:normal][https://www.google.com/search?] using search engine "google". Num keywords=1, num pages for keyword=[1]
2015-04-28 10:30:01,008 - GoogleScraper - ERROR - Message: 'chromedriver' executable needs to be                 available in the path. Please look at                 http://docs.seleniumhq.org/download/#thirdPartyDrivers                 and read up at                 http://code.google.com/p/selenium/wiki/ChromeDriver

2015-04-28 10:30:01,009 - GoogleScraper - WARNING - [google]SelScrape: Aborting due to no available selenium webdriver.
Exception in thread [google]SelScrape:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/root/GoogleScraper/env/lib/python3.4/site-packages/GoogleScraper/selenium_mode.py", line 580, in run
    self.webdriver.set_window_size(400, 400)
AttributeError: 'SelScrape' object has no attribute 'webdriver'
````

This was after removing `self._set_xvfb_display()` from `/GoogleScraper/env/lib/python3.4/site-packages/GoogleScraper/selenium_mode.py`. I'm on Ubuntu and I've already done `apt-get install chromium-chromedriver-dbg`.

**Comment by frandres** [comment]
You need to make sure that the driver is on the $PATH environment variable. 

To do this, you can find the path of chromedriver by doing:

locate chromedriver

in a Linux console. However you should normally find it at /usr/lib/chromium-browser/ if I'm not mistaken.

Then, you need to add it to the $PATH variable. You can do that by modifying the .bashrc file in your home directory and adding the following:

export PATH=$PATH:<PATH TO WHERE YOUR CHROMEDRIVER IS>

You can modify this file by doing:

cd
vim (or nano) .bashrc

**Comment by jamesspittal** [comment]
Ah, good point. Didn't read the error message properly.

`echo "export PATH=$PATH:/usr/lib/chromium-browser" >> ~/.bashrc` did the trick perfectly (after using `locate chromedriver` to confirm that it was indeed in `/usr/lib/chromium-browser/chromedriver`.

Ran it again, and it worked. Thanks @frandres

**Comment by jamesspittal** [comment]
I notice that you're using ChromeDriver 2.15.322448 and I'm on ChromeDriver 2.13 from the looks of things, so I'll try updating ChromeDriver.
